apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-demo
spec:
  template:
    metadata:
      name: countdown-demo
    spec:
      containers:
      - name: counter-demo
        image: centos:latest
        command:
          - "bin/bash"
          - "-c"
          - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never
