apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: container-demo
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
